### ISSUE TITLE
hey!

### ISSUE THREAD

**Issue by m113e55ml** [hellobbn/releases#1]
Hey! I appreciate your work!
I really don't want to bug you or something with these questions but I hope it's okay for you.
I would even donate a good amount to you!!
I see you're maintaining various xperia 1 and v models. Is it possible in the near future to add support for xperia 5 v pdx237?
Or is it possible to just flash the 1V zip's to my 5V?
I'm so sorry...

**Comment by hellobbn** [comment]
Hi, some work is need to support 5V. And if someone is interested in working on it, it might be supported in the future.

Sadly, I don't have the 5V device, nor do I have the time to work on 5V. So you might need to wait for some others to work on 5V.
I think it is relatively easy.

**Comment by m113e55ml** [comment]
Thank you for responsing!
Okay I might try it myself, I don't have any knowledge in programming or porting whatsoever but I give it a shot.
Would that be easier to somehow "port" files from pdx234 to pdx237 any tips on that?

**Comment by hellobbn** [comment]
I wiil try to list possible places that will need to be changed:

android_device_sony_sm8550-common:
1. Add pdx237 here: https://github.com/LineageOS/android_device_sony_sm8550-common/blob/lineage-21/Android.mk#L9
2. Add xperia 1v specific handling here: https://github.com/LineageOS/android_device_sony_sm8550-common/blob/lineage-21/rootdir/init.sony.rc#L64-L74

android_device_sony_pdx234 -> android_device_sony_pdx237
1. Please refer to how pdx214 is adapted from pdx215: https://github.com/LineageOS/android_device_sony_pdx214/commit/a0d764217ad43a80b71ca8eb2c2fa6db37409922 and commits following that

Other notes: 
- Given taht you don't have any knowledge in programming or porting, it might be quite difficult. 
- If you haven't tried building a ROM yourself, try building one first, which will make you understand how the build system works.
- Sadly I don't have more detailed information on how to port.

**Comment by m113e55ml** [comment]
Great! I will read through tutorials and guides and just start with it. Thank you!
